[package]
name = "grack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
anyhow = "1.0.68"
itertools = "0.10.5"
json = "0.12.4"
vmap = "0.5.1"
